# Generated by Django 4.2.7 on 2023-12-19 07:35

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('faceauth', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
