# Generated by Django 4.2.7 on 2023-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceauth', '0003_facephoto_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facephoto',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
